name: "Crawl Packages"
on:
  workflow_dispatch: 
  schedule:
    - cron: "7 16 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config --global user.name 'Github Actions [dwelch2344]'
          git config --global user.email 'dwelch2344@users.noreply.github.com'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm i

      - name: Crawl
        env:
          NPM_TOKEN: "${{ secrets.NPMJS_TOKEN }}"
        run: |
          npm run crawl:prod 
          mkdir -p archive
          cp data/*.json archive
          
      - name: create new branch
        run: |
          DATE=$(date '+%Y-%m-%d')
          git checkout -b "crawl-$DATE"
          
          git add -A
          git commit -m "Crawled on $DATE"
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Push the branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "crawl-${{env.DATE}}"
      
      - name: Stash the stats
        run: |
          echo "Copying archive to $RUNNER_TEMP"
          cp -R archive $RUNNER_TEMP

      - uses: actions/checkout@v4
        with:
          ref: archive
        
      - name: Archive the stats
        run: |
          echo "Restoring stats from $RUNNER_TEMP"
          ls -alh $RUNNER_TEMP/archive
          cp -R $RUNNER_TEMP/archive/*.json archive
          git add -A
          git commit -m "Crawled on $DATE"
          
      - name: Push the archive
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "archive"