name: "node index cache"
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cache:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        kind:
          - nodejs
          - iojs

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: npm run crawl:debug 
      - run: git diff && git status
      - run: |
          ls 
          ls data
          tree data

      # - name: commit changes
      #   uses: elstudio/actions-js-build/commit@v4
      #   with:
      #     commitMessage: "curl \"https://${{ matrix.kind }}.org/dist/index.tab\" (and .json)"